name: Run test android on pipeline

on:
  push:
    branches:
      - master

env:
  JAVA_VERSION: '17'
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository test
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Appium & UIAutomator2
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          Start-Job -ScriptBlock { appium }

      - name: Run Android Emulator & Execute Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: Pixel_6
          script: |
            echo "Emulator berhasil dinyalakan di GitHub Actions!"
            ./gradlew test
